[features]
seeds = false
skip-lint = false
[programs.devnet]
swap = "4PhKq1ovKkPYhdBxbeMrQWoBKHbpgCJsqzHiTuyGQjrT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/vinhtrinhvan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
